---
title: HW 03
author: STA 198 Summer 2020 (Jiang)
date: "Due: Tuesday, June 09, 2020 at 11:59p"
output:
  rmarkdown::html_document:
    css: "./sta199-hw.css"
    toc: FALSE
---

Click on the following link to clone the assignment repository into your own private repository, and then create an RStudio Cloud project in the class workspace named "HW-03" using this private repo (you may need to install some packages): 

[https://classroom.github.com/a/6AmStcKQ](https://classroom.github.com/a/6AmStcKQ)

**Reminder**: You must turn in a knitted .pdf file to Gradescope by 11:59p US Eastern on June 9th in order to receive credit. Late work is not accepted. 

1. **3 points** Make sure your GitHub repository for this assignment has at least three commits, each with a meaningful commit message.
2. **12 points** Determine which probability distribution would be **most** appropriate for modeling the quantity of interest: Bernoulli, Binomial, Normal, or Poisson. No explanation is required.
- (A)...average tumor volume in rats exposed to a carcinogen
- (B)...number of children in a pre-school classroom who are allergic to peanuts 
- (C)...number of deaths due to opioid overdose in N.C. in a given month
- (D)...whether a stroke patient has a family history of cardiovascular disease
- (E)...number of endangered coral colonies encountered during a dive
- (F)...mean maximum body temperature among malaria patients experiencing fever

For Exercises 3-6, explain why it would be *inappropriate* to model each quantity with the specified distribution.

3. **3 points** Modeling the five-year survival probability after colon cancer diagnosis with a Bernoulli distribution
4. **3 points** Modeling the percentage of US children who do not get adequate exercise with a binomial distribution
5. **3 points** The number of servings of vegetables eaten per week in a family using a normal distribution
6. **3 points** The number of new COVID-19 patients in Durham, N.C. using a Poisson distribution
7. **6 points** Explain why the graphs below do not depict valid density functions
```{r, echo = F}
x <- seq(-10, 10, by = 0.01)
y <- -abs(x) + 10
plot(x, y, type = "l",xlab = "x", ylab = "f(x)", main = "(A)")
x <- seq(-4, 4, by = 0.01)
y <- dnorm(x) -0.2
plot(x, y, type = "l",xlab = "x", ylab = "f(x)", main = "(B)")
```
8. **3 points** Consider the mean and variance of a binomial distribution. For any arbitrary sample size $n$ and non-zero success probability  $p$, is the mean larger than the variance, the variance larger than the mean, or are they equal? Explain.
9. **3 points** Suppose you are investigating the number of heart attacks experienced by heart disease patients from age 65 to death. In calculating basic sample statistics from a cohort of patients, we have the following summary statistics: sample mean of 0.8, sample minimum of 0, sample maximum of 8, sample median of 0, and sample variance of 3.5. Explain whether you think or do not think these data come from a Poisson distribution and why.
10. **3 points** Suppose we standardize an observation from a normally distributed random variable. Does knowing its z-score tell us anything about its mean and variance? Explain.

FEV$_1$, or forced expiratory volume in one second, is the volume of air that can be forcibly expelled in one second after taking a full breath. Suppose in a population of non-smoking 50-year old men, FEV$_1$ is normally distributed with mean 4.0 liters and standard deviation 0.5 liters, and that in a population of 50-year old male smokers, FEV$_1$ is normally distributed with mean 3.5 liters and standard deviation 0.5 liters. Let an FEV$_1$ of 2.5 or less be defined to be evidence of lung function impairment (e.g., breathlessness when walking, etc.).

11. **4 points** Suppose 20\% of men in this population smoke. What is the approximate probability that a randomly selected man has impaired lung function?
12. **4 points** What is the approximate probability that a randomly selected non-smoker in this population has a lower FEV$_1$ than the average FEV$_1$ among smokers?




